#CALCULATING FLOOR NUMBER DIFFERENCES BETWEEN THAT OF THE US AND EUROPE
c= input(' EUROPE FLOOR NUMBER? ')
#c BECOMES A Str() INPUT CONVERTED TO int()
c = int(c)
v = c + 1
print(' US FLOOR NUMBER', v) 