nam = input('WHO ARE YOU? ')
print('welcome',nam)
v = input("WHERE DO YOU SCHOOL? ")
print(v,"is a very nice school!")
C = input("ARE YOU A SERIOUS STUDENT?")
print('That is very good!',nam)
print('I would love you to learn very hard to pass your BECE OK!')
t = input("I HOPE YOU WILL?")
print('Ofcourse I believe in you !! kill all the papers',nam)